function graph_testData_plot
load('graph_testData','graphVector_solved',...
    'graphVectorMedium_solved','pqOpenMedium','closedMedium')
figure(1)
graph_plot(graphVector_solved,...
    'nodeLabels',true,'edgeWeights',true,...
    'backpointerCosts',true,...
    'heuristic',true,...
    'start',4,'goal',2)
title('graphVector_solved')
figure(2)
graph_plot(graphVectorMedium_solved,...
    'start',1,'goal',15,...
    'closed',closedMedium,'pqOpen',pqOpenMedium,...
    'backpointerCosts',true,...
    'heuristic',true,...
    'best',3,'neighbors',[4 6])
title('graphVectorMedium_solved')


